### ISSUE TITLE
Enhance libjsonnet BinaryLabels function

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox#22]
It should be possible to pass "options" parameter in BinaryLabels, as it's supported here

https://github.com/gfi-centre-ouest/docker-devbox-ddb/blob/ae962198abdaff1965ddcc819dcfa072388b8edb/ddb/feature/docker/binaries.py#L34-L42

Also, only name parameter should be mandatory, others should be optionals

Parameters should be defined in this order: name, workdir, args, options.

**Comment by darkanakin41** [comment]
Handled in #23 processing : 2 new functions have been added : 
* BinaryOptions(name, options, condition = null, index = null):
    * name : the name of the command
    * options : the list of options to add to the command
    * condition : the condition to be eval when generating the command (used in run)
    * index : not yet implemented but will grant the possibility to add multiple options with differents conditions
