### ISSUE TITLE
Add support for conditions for Docker binaries options

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox#23]
Binaries generated from docker compose should support some kind of evaluate options, with arguments given in the context.

    ddb.emit.docker:binary[npm](name): npm,
    ddb.emit.docker:binary[npm](workdir): /app
    ddb.emit.docker:binary[npm](options): -l traefik.enable=false
    ddb.emit.docker:binary[npm](options-condition): '"run serve" not in args'

In this case, -l traefik.enable=false option would be added only if arguments given to the command doesn't contains run serve.

**Comment by Toilal** [comment]
As a second step, it would be nice to be able to define many conditions and many possible options

    ddb.emit.docker:binary[npm](name): npm,
    ddb.emit.docker:binary[npm](workdir): /app
    ddb.emit.docker:binary[npm](options)(c1): -l traefik.enable=false
    ddb.emit.docker:binary[npm](options-condition)(c1): '"run serve" not in args'
    ddb.emit.docker:binary[npm](options)(c2): --verbose
    ddb.emit.docker:binary[npm](options-condition)(c2): '"verbose" in args'
    ddb.emit.docker:binary[npm](options): --fallback  # Would be used if NO condition match

**Comment by darkanakin41** [comment]
The first part is in PR [gfi-centre-ouest/docker-devbox-ddb#PR11](https://github.com/gfi-centre-ouest/docker-devbox-ddb/pull/11)

**Comment by Toilal** [comment]
Implemented by https://github.com/gfi-centre-ouest/docker-devbox-ddb/commit/9a4427727bea329f0a7b1a229c50fe91ecbf0781
